/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooqdata.tables.Lot;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LotRecord extends UpdatableRecordImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>purchase.lot.lot_id</code>.
     */
    public void setLotId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>purchase.lot.lot_id</code>.
     */
    public Integer getLotId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>purchase.lot.lot_name</code>.
     */
    public void setLotName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>purchase.lot.lot_name</code>.
     */
    public String getLotName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>purchase.lot.customer_code</code>.
     */
    public void setCustomerCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>purchase.lot.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>purchase.lot.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>purchase.lot.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>purchase.lot.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>purchase.lot.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>purchase.lot.nds_rate</code>.
     */
    public void setNdsRate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>purchase.lot.nds_rate</code>.
     */
    public String getNdsRate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>purchase.lot.place_delivery</code>.
     */
    public void setPlaceDelivery(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>purchase.lot.place_delivery</code>.
     */
    public String getPlaceDelivery() {
        return (String) get(6);
    }

    /**
     * Setter for <code>purchase.lot.date_delivery</code>.
     */
    public void setDateDelivery(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>purchase.lot.date_delivery</code>.
     */
    public LocalDateTime getDateDelivery() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LotRecord
     */
    public LotRecord() {
        super(Lot.LOT);
    }

    /**
     * Create a detached, initialised LotRecord
     */
    public LotRecord(Integer lotId, String lotName, String customerCode, BigDecimal price, String currencyCode, String ndsRate, String placeDelivery, LocalDateTime dateDelivery) {
        super(Lot.LOT);

        setLotId(lotId);
        setLotName(lotName);
        setCustomerCode(customerCode);
        setPrice(price);
        setCurrencyCode(currencyCode);
        setNdsRate(ndsRate);
        setPlaceDelivery(placeDelivery);
        setDateDelivery(dateDelivery);
        resetTouchedOnNotNull();
    }
}
